<?php
/**
 * @package   	OneAll Single Sign-On
 * @copyright 	Copyright 2011-2017 http://www.oneall.com/
 * @license   	GNU/GPL 2 or later
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307,USA.
 *
 * The "GNU General Public License" (GPL) is available at
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 */

// OneAll Site Subdomain
$oneall_site_subdomain = Mage::getStoreConfig ('oneall_singlesignon/general/subdomain');

// Include Library
if (! empty ($oneall_site_subdomain))
{
	// Customer is logged in
	if(Mage::getSingleton('customer/session')->isLoggedIn())
	{
		// Logged in
		$is_logged_in = true;
	
		// Read Customer
		$customer = Mage::getSingleton('customer/session')->getCustomer();
	
		// Check if we sso_session_token for this customer
		$session = Mage::getModel ('oneall_singlesignon/session')->load ($customer->getEntityId(), 'customer_id');
		$sso_session_token = $session->sso_session_token;
	}
	// Customer is not logged in
	else
	{
		// Not logged in
		$is_logged_in = false;
	}
	
	// Library
	$library_js = <<<HEREDOC
	var have_oa_lib = (have_oa_lib || false);
	(function(){if (!have_oa_lib){
		var lib = document.createElement('script');
		lib.type = 'text/javascript'; lib.async = true;
		lib.src = '//$oneall_site_subdomain.api.oneall.com/socialize/library.js'
		var node = document.getElementsByTagName('script')[0];
		node.parentNode.insertBefore(lib, node);
		have_oa_lib = true;
	}})();

HEREDOC;
	
	if ($is_logged_in)
	{
		if ( ! empty ($sso_session_token))
		{
?>
<!-- OneAll.com / Single Sign-On for Magento -->
<script type="text/javascript">
//<![CDATA[
<?php echo $library_js; ?>
	var _oneall = (_oneall || []);			
	_oneall.push(['single_sign_on', 'do_register_sso_session', '<?php echo $sso_session_token; ?>']);
 //]]>
</script>
<?php  
		}
	}
	else
	{
?>
<!-- OneAll.com / Single Sign-On for Magento -->
<script type="text/javascript">
//<![CDATA[
<?php echo $library_js; ?>
	var _oneall = (_oneall || []);
	_oneall.push(['single_sign_on', 'set_callback_uri', (window.location.href + ((window.location.href.split('?')[1] ? '&amp;' : '?') + 'oneall=sso'))]);
	_oneall.push(['single_sign_on', 'do_check_for_sso_session']);
 //]]>
</script>
<?php 	
	}
}